// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qpthkgtbkmibznzcodmt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwdGhrZ3Ria21pYnpuemNvZG10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAxNjk0NTAsImV4cCI6MjA3NTc0NTQ1MH0.oB7Zk1hVpsf9M5BRf3ZDf6YZm6YERs6Gjp1HcNPM6hA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});